[googledrive]
type = drive
client_id = 723280124028-v03t4u1ds6lvalr7l1ovmhuqo65e8b8p.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AZYkNZhuhbj98TdXFDVKixOaKyi6vIHuXG4t3-tBtzNPAnhC3IC_XDqZ3f62idKTR1SvfmqSNkcyxzt9VzCyonF_v2-vPCYsNYGR2FPuE0CY9KiT05CMQ5IXTjzpWYcEIRcKlTh20vMWqpjCnS8UAZiw5g0U3J7heR8J8qT7UQaCgYKAUYSARMSFQHGX2MiGAmmz-xCBoW2zsM3p8jurw0177","token_type":"Bearer","refresh_token":"1//09UEmJ0KabxFcCgYIARAAGAkSNwF-L9IrtEvDidksr0pxb8woCLEw2ewYTyJvGZ6wxCcBfx8cRxBQeR6064ahQ2hKNa-84c3YhtQ","expiry":"2025-04-14T18:56:06.963589305+02:00"}
team_drive = 

[fritznas]
type = smb
host = fritz.box
user = Matthias
pass = WUkiZVWEUpe-1Bf-1mneTUMVA2EZu_r4NXY

