[googledrive]
type = drive
client_id = 723280124028-v03t4u1ds6lvalr7l1ovmhuqo65e8b8p.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AW4Xtxh1eO28MmpsXoFafzXO45JmAQ8urqS-S2Dvt7O-hNKGT_rlk24IEy8Ac4oKyUdHwEnV0gauxpw5nrvg5aBNU1werM9N6nKmXIal4RLyWW_21-yLknEU29js8APLWmOAfcfgdZrFdoN3gLzpLSDJWgeL3jjNh3bgJm2EkwaCgYKAeISARMSFQHGX2Mil1p0M2u7lFJnO0cj2u-H7Q0177","token_type":"Bearer","refresh_token":"1//09rEICoinmRUYCgYIARAAGAkSNwF-L9IrFNL8OwBFprZa00_t5lmBeFWAx4GWTGFMN9TXWcDjdYS7Tc5He6mvsGyrnG-FtV9DIlQ","expiry":"2025-06-18T18:01:19.624065368+02:00"}
team_drive = 

[fritznas]
type = smb
host = fritz.box
user = Matthias
pass = WUkiZVWEUpe-1Bf-1mneTUMVA2EZu_r4NXY

