[googledrive]
type = drive
client_id = 723280124028-v03t4u1ds6lvalr7l1ovmhuqo65e8b8p.apps.googleusercontent.com
client_secret = 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
scope = drive
token = {"access_token":"ya29.a0AZYkNZimpfrurqPz0HQqa_p00STs5GmM0-e-XQUMBpO4SFOVZga8FNUEltU6ESoWfXiznUKhrQZ4VtN1y77Td1_N4aM7pLOJ1_rN7iVzuftKsfImZYUGAaLdEITbbS0y2-WZvIavHM6YWnHcT1h40t2sgCsWXM2_pzHGBxL_-waCgYKAfISARMSFQHGX2Milhk3w8M9X-ym_y42t_y5QQ0177","token_type":"Bearer","refresh_token":"1//09UEmJ0KabxFcCgYIARAAGAkSNwF-L9IrtEvDidksr0pxb8woCLEw2ewYTyJvGZ6wxCcBfx8cRxBQeR6064ahQ2hKNa-84c3YhtQ","expiry":"2025-04-10T14:27:21.558772482+02:00"}
team_drive = 

